[sidebar]
[sidebar.a]
title = "Documentation"
[sidebar.a.overview]
title = "Overview"
path = "/docs/a1.overview.html"

[sidebar.b]
title = "Introduction"
[sidebar.b.intro]
title = "Introduction to the Game Industry"
path = "/docs/b1.intro.html"
[sidebar.b.install]
title = "Installing the Engine"
path = "/docs/b2.installing_unity.html"
[sidebar.b.engine]
title = "Unity Interface"
path = "/docs/b3.unity_interface.html"

[sidebar.c]
title = "Programming"
[sidebar.c.variables]
title = "What are Variables"
path = "/docs/c1.variables.html"
[sidebar.c.functions]
title = "What are Functions"
path = "/docs/c2.functions.html"
[sidebar.c.ifstatement]
title = "If Statement"
path = "/docs/c3.if.html"
